version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - nginx_network
      - postgres_db_network  # <-- connect to the bridge
    depends_on:  # <-- wait for db to be "ready" before starting the app
      - postgres_db

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  postgres_db:  # <-- IMPORTANT: same name as in DATABASES setting, otherwise Django won't find the database!
    image: postgres:10
    env_file:  # <-- we use the previously defined values
      - config/db/postgres_db_env
    networks:  # <-- connect to the bridge
      - postgres_db_network
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  postgres_db_network:  # <-- add the bridge
    driver: bridge

volumes:
  postgres_db_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume